services:
  jekyll:
    build: .
    image: bharat-govil-al-folio:local
    command: >
      bundle exec jekyll serve --host 0.0.0.0 --port 8080
      --livereload --force_polling --destination /tmp/_site
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:35729:35729"
    volumes:
      - .:/srv/jekyll
    environment:
      JEKYLL_ENV: development
